defmodule DhcWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dhc

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dhc_key",
    signing_salt: "8dIa9x5k",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Authenticated, WebSocket-only socket for Notification invalidation signals.
  #
  # Phoenix 1.8 native `auth_token: true` exposes the JS client's `authToken`
  # option as `connect_info[:auth_token]` in `UserSocket.connect/3` (the token is
  # carried in the `Sec-WebSocket-Protocol` subprotocol, keeping it out of the
  # URL). Long polling is intentionally disabled: this is a best-effort
  # invalidation signal only, and disabling longpoll avoids a second transport
  # lifecycle and CORS handling. See
  # docs/secure-phoenix-channel-browser-integration.md and
  # docs/phoenix-notification-realtime-migration-spec.md.
  socket "/socket", DhcWeb.UserSocket,
    websocket: true,
    longpoll: false,
    auth_token: true

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dhc,
    gzip: not code_reloading?,
    only: DhcWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dhc
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug DhcWeb.Plugs.Cors

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {DhcWeb.CacheBodyReader, :read_body, []}

  plug Sentry.PlugContext

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DhcWeb.Router
end
