import Config

# Configure your database. Prefer DATABASE_URL so dev, seeds, and production
# use the same connection convention. Fall back to the local Supabase Postgres
# defaults only when DATABASE_URL is absent.
repo_config =
  if database_url = System.get_env("DATABASE_URL") do
    [url: database_url]
  else
    [
      username: System.get_env("POSTGRES_USER", "postgres"),
      password: System.get_env("POSTGRES_PASSWORD", "postgres"),
      hostname: System.get_env("POSTGRES_HOST", "localhost"),
      port: String.to_integer(System.get_env("POSTGRES_PORT", "54322")),
      database: System.get_env("POSTGRES_DB", "postgres")
    ]
  end

config :dhc, Dhc.Repo,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :dhc, Dhc.Repo, repo_config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :dhc, DhcWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "mEHPN3I43Gf0FBejkN4LFcbkVzS/towwtozu5LqrGTe/vfj4bpSNgdcRbiTNUt4d",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :dhc, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Discord webhook URL (not sent in dev — messages are logged instead)
config :dhc, :discord_webhook_url, System.get_env("DISCORD_WEBHOOK_URL")
# Loops API key (not sent in dev — payloads are logged instead)
config :dhc, :loops_api_key, System.get_env("LOOPS_API_KEY")
# Stripe API (not called in dev — sync logs and returns :ok)
config :dhc, :stripe_secret_key, System.get_env("STRIPE_SECRET_KEY")
config :dhc, :stripe_api_url, "https://api.stripe.com"
config :dhc, :stripe_api_version, "2025-10-29.clover"
config :dhc, :stripe_webhook_secret, System.get_env("STRIPE_WEBHOOK_SIGNING_SECRET")

config :dhc,
       :supabase_url,
       System.get_env("SUPABASE_URL") || System.get_env("PUBLIC_SUPABASE_URL")

config :dhc,
       :supabase_anon_key,
       System.get_env("SUPABASE_ANON_KEY") || System.get_env("PUBLIC_SUPABASE_ANON_KEY")

config :dhc,
       :supabase_service_role_key,
       System.get_env("SUPABASE_SERVICE_ROLE_KEY") || System.get_env("SERVICE_ROLE_KEY")

config :dhc,
       :app_url,
       System.get_env("APP_URL") || System.get_env("PUBLIC_SITE_URL") ||
         System.get_env("SITE_URL") || "http://localhost:5173"

config :dhc, :environment, :development

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
