defmodule Dhc.Repo.Migrations.CreateUsersAndRoles do
  use Ecto.Migration

  def up do
    # ── user_profiles ───────────────────────────────────────
    create table(:user_profiles, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")

      # Ecto silently ignores `unique: true` on `add/3` (column_options only
      # handles :default/:null/:collation) — it does NOT emit a UNIQUE
      # constraint. The FK in 20260512000008 (club_activity_registrations ->
      # user_profiles.supabase_user_id) requires supabase_user_id to be
      # unique, so create the index explicitly here.
      add :supabase_user_id, references(:users, prefix: "auth", type: :uuid, on_delete: :nothing)

      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :is_active, :boolean, default: true
      add :medical_conditions, :text
      add :date_of_birth, :date, null: false
      add :gender, :gender
      add :pronouns, :text
      add :phone_number, :text, null: false, default: ""
      add :social_media_consent, :social_media_consent, default: "no"
      add :customer_id, :text
      add :waitlist_id, references(:waitlist, type: :uuid, on_delete: :nothing)

      # Match the original Supabase schema (20241113174153_users_schema.sql):
      # `created_at`/`updated_at`, NOT Ecto's default `inserted_at`. The
      # `UserProfile` schema declares `timestamps(inserted_at: :created_at)`,
      # so the DB column must be `created_at` for the schema to read it.
      timestamps(type: :timestamptz, inserted_at: :created_at)
    end

    # search_text is a GENERATED ALWAYS AS STORED tsvector (matching Supabase's
    # 20241125103648_normalize_user_profiles.sql). Ecto's `add/3` can't express
    # generated columns, so use raw SQL. Generated columns are auto-populated
    # from first_name/last_name and cannot be inserted into — the UserProfile
    # schema deliberately doesn't declare `search_text`, so inserts skip it.
    execute """
    ALTER TABLE user_profiles
    ADD COLUMN search_text tsvector
      GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(first_name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(last_name, '')), 'A')
      ) STORED
    """

    # supabase_user_id must be unique — referenced by FK in a later migration
    # (club_activity_registrations.member_user_id -> user_profiles.supabase_user_id).
    create unique_index(:user_profiles, [:supabase_user_id])

    execute "CREATE INDEX idx_user_profiles_search ON user_profiles USING GIN (search_text)"
    create index(:user_profiles, [:waitlist_id])
    create index(:user_profiles, [:first_name, :last_name])
    create index(:user_profiles, [:first_name, :last_name, :waitlist_id])

    execute """
    ALTER TABLE user_profiles
    ADD CONSTRAINT dob_age_check CHECK (
      date_of_birth < CURRENT_DATE AND
      EXTRACT(YEAR FROM AGE(CURRENT_DATE, date_of_birth)) >= 16
    )
    """

    # ── user_roles ──────────────────────────────────────────
    # `id bigint generated by default as identity primary key` isn't expressible
    # via Ecto's `:default` (it wraps the fragment in `DEFAULT "..."`, producing
    # invalid SQL like `DEFAULT generated by default as identity`). IDENTITY is
    # a column *constraint*, not a default expression, so use raw SQL — matches
    # the original supabase/migrations/20241113174153_users_schema.sql:39.
    execute """
    CREATE TABLE "user_roles" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "user_id" uuid NOT NULL,
      CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE,
      "role" role_type NOT NULL,
      UNIQUE ("user_id", "role")
    )
    """

    create index(:user_roles, [:role, :user_id, :id])

    # ── user_audit_log ──────────────────────────────────────
    create table(:user_audit_log, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")
      add :user_id, references(:users, prefix: "auth", type: :uuid, on_delete: :nothing)
      add :action, :text, null: false
      add :details, :map
      add :ip_address, :text
      add :created_at, :timestamptz, default: fragment("NOW()")
    end

    create index(:user_audit_log, [:created_at])

    # ── waitlist_guardians ──────────────────────────────────
    # Must come after user_profiles (FK reference)
    create table(:waitlist_guardians, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")

      add :profile_id, references(:user_profiles, type: :uuid, on_delete: :delete_all),
        null: false

      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :phone_number, :text, null: false
      add :created_at, :timestamptz, default: fragment("NOW()")
    end

    create index(:waitlist_guardians, [:profile_id])
  end

  def down do
    drop table(:waitlist_guardians)
    drop table(:user_audit_log)
    drop table(:user_roles)
    drop table(:user_profiles)
  end
end
