defmodule Dhc.Repo.Migrations.CreateUsersAndRoles do
  use Ecto.Migration

  def up do
    # ── user_profiles ───────────────────────────────────────
    create table(:user_profiles, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")

      add :supabase_user_id, references(:users, prefix: "auth", type: :uuid, on_delete: :nothing),
        unique: true

      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :is_active, :boolean, default: true
      add :medical_conditions, :text
      add :date_of_birth, :date, null: false
      add :gender, :gender
      add :pronouns, :text
      add :phone_number, :text, null: false, default: ""
      add :social_media_consent, :social_media_consent, default: "no"
      add :customer_id, :text
      add :waitlist_id, references(:waitlist, type: :uuid, on_delete: :nothing)
      # Search vector for full-text search (generated in Supabase, stored as simple column here)
      add :search_text, :tsvector

      timestamps(type: :timestamptz)
    end

    execute "CREATE INDEX idx_user_profiles_search ON user_profiles USING GIN (search_text)"
    create index(:user_profiles, [:waitlist_id])
    create index(:user_profiles, [:first_name, :last_name])
    create index(:user_profiles, [:first_name, :last_name, :waitlist_id])

    execute """
    ALTER TABLE user_profiles
    ADD CONSTRAINT dob_age_check CHECK (
      date_of_birth < CURRENT_DATE AND
      EXTRACT(YEAR FROM AGE(CURRENT_DATE, date_of_birth)) >= 16
    )
    """

    # ── user_roles ──────────────────────────────────────────
    create table(:user_roles, primary_key: false) do
      add :id, :bigint, primary_key: true, default: fragment("generated by default as identity")

      add :user_id, references(:users, prefix: "auth", type: :uuid, on_delete: :delete_all),
        null: false

      add :role, :role_type, null: false
    end

    create unique_index(:user_roles, [:user_id, :role])
    create index(:user_roles, [:role, :user_id, :id])

    # ── user_audit_log ──────────────────────────────────────
    create table(:user_audit_log, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")
      add :user_id, references(:users, prefix: "auth", type: :uuid, on_delete: :nothing)
      add :action, :text, null: false
      add :details, :map
      add :ip_address, :text
      add :created_at, :timestamptz, default: fragment("NOW()")
    end

    create index(:user_audit_log, [:created_at])

    # ── waitlist_guardians ──────────────────────────────────
    # Must come after user_profiles (FK reference)
    create table(:waitlist_guardians, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")

      add :profile_id, references(:user_profiles, type: :uuid, on_delete: :delete_all),
        null: false

      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :phone_number, :text, null: false
      add :created_at, :timestamptz, default: fragment("NOW()")
    end

    create index(:waitlist_guardians, [:profile_id])
  end

  def down do
    drop table(:waitlist_guardians)
    drop table(:user_audit_log)
    drop table(:user_roles)
    drop table(:user_profiles)
  end
end
