defmodule Dhc.Auth do
  @moduledoc """
  The Authentication context — Phoenix-owned login, magic-link, and session
  boundary (ADR 0009, ADR 0010, ADR 0011, ALE-165).

  This context is the single seam for authentication state. It owns:

    * **Principal** lookup by normalized login email (`get_principal_by_email/1`).
    * **Magic-link** issue and consume: `deliver_magic_link/2` enqueues a
      Loops email via `Dhc.Email.Worker`; `consume_magic_link/1` verifies,
       deletes outstanding magic-link tokens for the principal, confirms the
       email on first use, and creates a new session only when the Member has
       access.
    * **Session** lifecycle: proof-oriented sign-in, `get_principal_by_session_token/1`,
      `delete_session_token/1`, and `delete_all_principal_sessions/1`. Sessions
       are opaque, DB-backed, 30-day absolute lifetime (no sliding refresh).
    * **Access** projection: `apply_member_access/2` serializes projection
      changes with sign-in, revokes every authentication token, and disconnects
      established sockets when access is lost. `load_session_principal/1`
      returns current roles and access for authenticated requests.

  ## Email normalization

  Every email input goes through `Dhc.Auth.Principal.normalize_email/1`. The
  DB column is `citext` so case-insensitive lookups are guaranteed at both
  layers.

  ## Non-enumerating behavior

  `deliver_magic_link/2` returns `{:ok, :sent}` for any well-formed email
  — whether or not a Principal exists — so a caller cannot probe which
  addresses are registered. Rate limiting (3/email/15min, 10/IP/hour) is
  enforced at the controller layer (`DhcWeb.Plugs.MagicLinkRateLimit`) so the
  context stays focused on state.

  ## What this context does NOT do

    * Member / Membership / Role policy. Membership decides the access value;
      Authentication applies that projection atomically with Session cleanup.
    * Invitation Acceptance principal creation (ALE-162).
    * Migration / cutover (ALE-163, ALE-166).
  """

  import Ecto.Query, warn: false
  alias Dhc.Repo
  alias Dhc.Auth.{DiscordSubjectLock, ExternalIdentity, Principal, PrincipalToken}
  alias Dhc.Discord.StagedAssignment
  alias Dhc.MemberProfiles.MemberProfile
  alias Dhc.Onboarding.InvitationAcceptanceDiscordSubjectClaim
  alias Dhc.UserProfiles.UserProfile

  ## Database getters

  @doc """
  Fetches a Principal by its canonical login email.

  Email is normalized before lookup. Returns `nil` if no Principal matches —
  callers must treat this the same as a Principal that exists but is inactive
  (see `deliver_magic_link/2`).
  """
  def get_principal_by_email(email) when is_binary(email) do
    Repo.get_by(Principal, email: Principal.normalize_email(email))
  end

  def get_principal_by_email(nil), do: nil

  @doc """
  Fetches a Principal by id. Raises `Ecto.NoResultsError` if missing.
  """
  def get_principal!(id), do: Repo.get!(Principal, id)

  @doc """
  Registers a Principal with a normalized email. Used today only by tests and
  (later) by Invitation Acceptance (ALE-162) — never by a public sign-up.
  """
  def register_principal(attrs) do
    %Principal{}
    |> Principal.email_changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Registers a Principal with a specific id and normalized email.

  ALE-162 (ADR 0010): Invitation Acceptance creates the Principal inside the
  acceptance transaction with `id = invitation.prospective_principal_id` (the fresh Phoenix UUID
  minted at issue time). This keeps the post-M1 invariant
  `principals.id == user_profiles.supabase_user_id == member_profiles.id` from
  the moment the record set is born — there is never a Member without a
  Principal or a Principal without a Member.

  The id is set on the struct directly (not via the changeset) because
  `email_changeset/2` does not cast `:id` (it is autogenerated for the normal
  registration path). The email is still normalized and validated.
  """
  @spec register_principal_with_id(Ecto.UUID.t(), map()) ::
          {:ok, Principal.t()} | {:error, Ecto.Changeset.t()}
  def register_principal_with_id(id, attrs) when is_binary(id) do
    %Principal{id: id}
    |> Principal.email_changeset(attrs)
    |> Repo.insert()
  end

  ## Discord External Identity

  @doc """
  Signs in the Principal linked to Discord's immutable provider subject.

  Profile claims are never used to select a Principal, replace an existing
  link, or update the Principal's authoritative email. An unlinked subject can
  authenticate only by promoting its exact approved Staged Assignment.
  """
  def sign_in_with_discord(%{"sub" => subject} = claims)
      when is_binary(subject) and subject != "" do
    case Repo.one(
           from(identity in ExternalIdentity,
             where:
               identity.provider == "discord" and identity.provider_subject == ^subject and
                 is_nil(identity.retired_at)
           )
         ) do
      %ExternalIdentity{} = identity ->
        if is_nil(identity.sign_in_disabled_at) do
          identity.principal_id
          |> get_principal!()
          |> establish_eligible_session()
        else
          {:error, :invalid}
        end

      nil ->
        sign_in_unlinked_discord_subject(subject, claims)
    end
  end

  def sign_in_with_discord(_claims), do: {:error, :invalid}

  # An approved roster assignment is proof-bound to the immutable Discord
  # subject. No mutable profile claim, including Discord email, can grant login
  # authority for an unlinked subject.
  defp sign_in_unlinked_discord_subject(subject, claims) do
    case promote_staged_discord_assignment(subject, claims) do
      {:ok, principal} ->
        # Promotion has committed before this separate, ordinary access-checked
        # session boundary runs. An inactive Member keeps the permanent link,
        # but no session is minted.
        establish_eligible_session(principal)

      {:error, reason} when reason in [:no_assignment, :invalid] ->
        {:error, :invalid}
    end
  end

  defp promote_staged_discord_assignment(subject, claims) do
    case Repo.one(
           from(a in StagedAssignment,
             where:
               a.provider == "discord" and a.provider_subject == ^subject and
                 a.state in ["proposed", "approved"],
             select: a.principal_id
           )
         ) do
      nil ->
        {:error, :no_assignment}

      principal_id ->
        safe_discord_transaction(fn ->
          # The shared lock order is Principal then subject. Re-read every
          # decision under those locks; the database constraint triggers are
          # the final cross-table invariant at commit.
          DiscordSubjectLock.lock_principal!(principal_id)
          DiscordSubjectLock.lock!(subject)

          assignment =
            Repo.one(
              from(a in StagedAssignment,
                where:
                  a.provider == "discord" and a.provider_subject == ^subject and
                    a.principal_id == ^principal_id,
                lock: "FOR UPDATE"
              )
            )

          existing_identity =
            Repo.one(
              from(identity in ExternalIdentity,
                where:
                  identity.provider == "discord" and identity.provider_subject == ^subject and
                    is_nil(identity.retired_at)
              )
            )

          cond do
            match?(%ExternalIdentity{principal_id: ^principal_id}, existing_identity) ->
              # A callback that began before another promotion committed may
              # arrive here with a stale pre-lock lookup. Observe the permanent
              # identity under the shared locks and continue through the same
              # post-commit session boundary as an ordinary linked sign-in.
              Repo.get!(Principal, principal_id)

            not is_nil(existing_identity) ->
              Repo.rollback(:invalid)

            is_nil(assignment) or assignment.state != "approved" ->
              Repo.rollback(:invalid)

            discord_subject_claimed?(subject) ->
              Repo.rollback(:invalid)

            Repo.exists?(
              from(e in ExternalIdentity,
                where:
                  e.provider == "discord" and is_nil(e.retired_at) and
                      (e.provider_subject == ^subject or e.principal_id == ^principal_id)
              )
            ) ->
              Repo.rollback(:invalid)

            true ->
              case linked_member_principal_locked(principal_id) do
                nil ->
                  Repo.rollback(:invalid)

                principal ->
                  # The approved assignment must cease being an active binding
                  # candidate before the permanent identity is inserted. The
                  # transition trigger appends the promotion audit in this same
                  # transaction; a later insert failure rolls all three writes
                  # back together.
                  assignment
                  |> StagedAssignment.transition_changeset(%{
                    state: "promoted",
                    terminal_at: DateTime.utc_now(),
                    terminal_actor_principal_id: principal_id,
                    reason_code: "oauth_sign_in"
                  })
                  |> Repo.update!()

                  case Repo.insert(discord_identity_changeset(principal, subject, claims)) do
                    {:ok, _identity} -> principal
                    {:error, _changeset} -> Repo.rollback(:invalid)
                  end
              end
          end
        end)
        |> case do
          {:ok, principal} -> {:ok, principal}
          {:error, _reason} -> {:error, :invalid}
        end
    end
  end

  @doc """
  Links Discord to a Principal that has already proved its identity through an
  authenticated Session. Discord's email is retained as metadata only and is
  not required to match the Principal's authoritative email.
  """
  def link_discord_identity(%Principal{} = principal, %{"sub" => subject} = claims)
      when is_binary(subject) and subject != "" do
    safe_discord_transaction(fn ->
      DiscordSubjectLock.lock_principal!(principal.id)
      DiscordSubjectLock.lock!(subject)
      principal = lock_principal!(principal.id)
      unless eligible_member_locked?(principal.id), do: Repo.rollback(:invalid)
      if discord_subject_claimed?(subject), do: Repo.rollback(:invalid)

      principal
      |> discord_identity_changeset(subject, claims)
      |> Repo.insert()
      |> case do
        {:ok, identity} -> identity
        {:error, _changeset} -> Repo.rollback(:invalid)
      end
    end)
    |> transaction_result()
  end

  def link_discord_identity(principal_id, claims) when is_binary(principal_id) do
    case Repo.get(Principal, principal_id) do
      %Principal{} = principal -> link_discord_identity(principal, claims)
      nil -> {:error, :invalid}
    end
  end

  def link_discord_identity(_principal, _claims), do: {:error, :invalid}

  defp discord_identity_changeset(principal, subject, claims) do
    metadata =
      Map.take(claims, [
        "email",
        "email_verified",
        "preferred_username",
        "picture",
        "username",
        "avatar"
      ])

    ExternalIdentity.create_changeset(%ExternalIdentity{}, principal, %{
      provider: "discord",
      provider_subject: subject,
      metadata: metadata
    })
  end

  defp discord_subject_claimed?(subject) do
    Repo.exists?(
      from(claim in InvitationAcceptanceDiscordSubjectClaim,
        where: claim.provider == "discord" and claim.provider_subject == ^subject
      )
    )
  end

  defp establish_eligible_session(principal) do
    Repo.transaction(fn ->
      unless eligible_member_locked?(principal.id), do: Repo.rollback(:invalid)
      %{principal: principal, session_token: insert_session!(principal)}
    end)
    |> transaction_result()
  end

  ## Magic link

  @doc """
  Enqueues a magic-link email to the Principal with the given email, if any.

  Returns `{:ok, :sent}` for any well-formed email. The caller cannot tell
  whether a Principal exists — this is the anti-enumeration contract. When no
  Principal exists, no email is enqueued and no token row is written.

  `magic_link_url_fun` is called with the URL-safe encoded token to build the
  link the recipient will click. It is invoked only when a Principal exists.
  """
  def deliver_magic_link(email, magic_link_url_fun)
      when is_function(magic_link_url_fun, 1) do
    if principal = get_principal_by_email(email) do
      {:ok, encoded_token, _row} = build_magic_link(principal)
      url = magic_link_url_fun.(encoded_token)
      enqueue_magic_link_email(principal, url)
    end

    {:ok, :sent}
  end

  defp build_magic_link(principal) do
    {encoded_token, row} = PrincipalToken.build_magic_link_token(principal)
    {:ok, _} = Repo.insert(row)
    {:ok, encoded_token, row}
  end

  defp enqueue_magic_link_email(principal, url) do
    # ALE-165: enqueue via the existing Oban email worker so magic-link
    # delivery goes through the same Loops / Sentry / retry path as
    # invitation and workshop emails. The Loops transactional ID is resolved
    # at send time from :loops_transactional_ids config (the "magicLink"
    # friendly name). The URL is passed as the `LoginLink` data variable —
    # the Loops "magic link" transactional template (`cma3yqgqw68tv9pm5v0si5ge3`)
    # renders `{{LoginLink}}`, so the key here must match the template.
    %{
      email: principal.email,
      transactional_id: "magicLink",
      data_variables: %{"LoginLink" => url}
    }
    |> Dhc.Email.Worker.new()
    |> Oban.insert()
  end

  @doc """
  Consumes a magic-link token and, for an eligible Member, establishes a
  session.

  Outcomes (all observable to the controller):

    * `{:ok, %{principal: principal, session_token: token}}` — the Principal
      is now logged in. The magic-link token row is deleted, any prior
      magic-link tokens for the principal are deleted, the Principal's
      `confirmed_at` is stamped on first consumption, and a fresh session
      row is inserted. The returned `session` projection was read while the
      Member access row was locked.
    * `{:error, :inactive_membership}` — the token is valid and consumed, but
      the Member does not currently have club access.
    * `{:error, :invalid}` — the token does not decode, has no row, has
      expired, or was sent to an email that no longer matches the Principal.
      The controller surfaces this as the same generic "invalid or expired"
      response it uses for an unknown token (non-enumerating).

  A valid token for an inactive Member is still consumed and confirms the
  Principal, but returns `:inactive_membership` and creates no Session.
  """
  def consume_magic_link(encoded_token) do
    case PrincipalToken.verify_magic_link_token_query(encoded_token) do
      {:ok, query} ->
        Repo.transaction(fn ->
          case Repo.one(query) do
            {principal, _token_row} ->
              eligible? = eligible_member_locked?(principal.id)
              consume_locked_magic_link(query, principal, eligible?)

            nil ->
              :invalid
          end
        end)
        |> case do
          {:ok, {:signed_in, result}} -> {:ok, result}
          {:ok, :inactive} -> {:error, :inactive_membership}
          {:ok, :invalid} -> {:error, :invalid}
          {:error, _reason} -> {:error, :invalid}
        end

      :error ->
        {:error, :invalid}
    end
  end

  defp delete_principal_magic_link_tokens(principal) do
    {count, _} =
      Repo.delete_all(
        from t in PrincipalToken,
          where: t.principal_id == ^principal.id and t.context == "login"
      )

    {:ok, count}
  end

  defp consume_locked_magic_link(query, principal, eligible?) do
    # Member-first lock ordering keeps concurrent proofs and access changes
    # from deadlocking while the token refetch preserves single-use behavior.
    case query |> lock("FOR UPDATE") |> Repo.one() do
      {_principal, token_row} ->
        with {:ok, _} <- Repo.delete(token_row),
             {:ok, _} <- delete_principal_magic_link_tokens(principal),
             {:ok, principal} <- maybe_confirm_principal(principal) do
          if eligible? do
            {:ok, session} = load_session_principal(principal)

            {:signed_in,
             %{
               principal: principal,
               session_token: insert_session!(principal),
               session: session
             }}
          else
            :inactive
          end
        else
          {:error, reason} -> Repo.rollback(reason)
        end

      nil ->
        :invalid
    end
  end

  defp maybe_confirm_principal(%Principal{confirmed_at: nil} = principal) do
    principal
    |> Principal.confirm_changeset()
    |> Repo.update()
  end

  defp maybe_confirm_principal(%Principal{} = principal), do: {:ok, principal}

  ## Session

  defp insert_session!(%Principal{} = principal) do
    {token, row} = PrincipalToken.build_session_token(principal)
    Repo.insert!(row)
    token
  end

  @doc """
  Looks up the Principal for a session token.

  Returns `{:ok, principal}` if the token exists, has not expired (30-day
  absolute), and the Principal row still exists. Returns `{:error, :invalid}`
  otherwise. The caller (request plug) additionally checks `is_active` and
  roles.
  """
  def get_principal_by_session_token(token) do
    {:ok, query} = PrincipalToken.verify_session_token_query(token)

    case Repo.one(query) do
      {principal, _row} -> {:ok, principal}
      nil -> {:error, :invalid}
    end
  end

  @doc """
  Resolves a valid raw session token to its non-secret row UUID.

  The UUID can be retained by a server-managed multi-request flow without
  duplicating the reusable bearer token. It is not accepted as an HTTP
  authentication credential.
  """
  def get_session_reference(token) when is_binary(token) do
    {:ok, query} = PrincipalToken.verify_session_token_query(token)

    case Repo.one(query) do
      {_principal, row} -> {:ok, row.id}
      nil -> {:error, :invalid}
    end
  end

  @doc """
  Revalidates a session row UUID and returns its Principal.

  Deleting or expiring the original Session invalidates the reference because
  both lookups target the same database row.
  """
  def get_principal_by_session_reference(reference) when is_binary(reference) do
    {:ok, query} = PrincipalToken.verify_session_reference_query(reference)

    case Repo.one(query) do
      {principal, _row} -> {:ok, principal}
      nil -> {:error, :invalid}
    end
  end

  @doc """
  Deletes the session token row matching the raw token. Idempotent — a
  second logout with the same cookie is a no-op.

  The incoming cookie is hashed (SHA-256) before lookup, matching
  `Dhc.Auth.PrincipalToken.build_session_token/1`.
  """
  def delete_session_token(token) do
    hashed_token = Dhc.Auth.PrincipalToken.hash_token(token)

    Repo.delete_all(from(PrincipalToken, where: [token: ^hashed_token, context: "session"]))

    :ok
  end

  @doc """
  Deletes every session for the given principal. Used by sign-out-everywhere
  and by email-change / access-loss revocation (per the spec).
  """
  def delete_all_principal_sessions(%Principal{} = principal) do
    Repo.delete_all(
      from t in PrincipalToken,
        where: t.principal_id == ^principal.id and t.context == "session"
    )

    :ok
  end

  @doc """
  Applies Membership's access decision to one or more Member projections.

  Projection rows are locked so this transition serializes with every sign-in
  path. Losing access updates the projections and removes all Session and
  socket tokens in the same transaction. After that transaction commits, all
  established sockets for the affected Principals are disconnected. Restoring
  access never creates a Session.
  """
  @spec apply_member_access(Ecto.UUID.t() | [Ecto.UUID.t()], boolean()) ::
          :ok | {:error, term()}
  def apply_member_access(profile_id, is_active)
      when is_binary(profile_id) and is_boolean(is_active) do
    apply_member_access([profile_id], is_active)
  end

  def apply_member_access(profile_ids, is_active)
      when is_list(profile_ids) and is_boolean(is_active) do
    if not is_active and Repo.in_transaction?() do
      {:error, :nested_transaction}
    else
      apply_member_access_outside_transaction(profile_ids, is_active)
    end
  end

  defp apply_member_access_outside_transaction(profile_ids, is_active) do
    profile_ids = Enum.uniq(profile_ids)

    Repo.transaction(fn ->
      profiles =
        UserProfile
        |> where([profile], profile.id in ^profile_ids)
        |> order_by([profile], profile.id)
        |> lock("FOR UPDATE")
        |> Repo.all()

      if length(profiles) != length(profile_ids), do: Repo.rollback(:not_found)

      from(p in UserProfile, where: p.id in ^profile_ids)
      |> Repo.update_all(set: [is_active: is_active, updated_at: DateTime.utc_now(:second)])

      principal_ids =
        profiles
        |> Enum.map(& &1.principal_id)
        |> Enum.reject(&is_nil/1)

      if not is_active and principal_ids != [] do
        Repo.delete_all(
          from t in PrincipalToken,
            where: t.principal_id in ^principal_ids and t.context in ["session", "socket"]
        )
      end

      principal_ids
    end)
    |> case do
      {:ok, principal_ids} ->
        if not is_active do
          Enum.each(principal_ids, &DhcWeb.UserSocket.disconnect/1)
        end

        :ok

      {:error, reason} ->
        {:error, reason}
    end
  end

  ## Socket tokens (ALE-164)

  @doc """
  Creates a short-lived socket token for the principal and returns the raw
  opaque token.

  The browser exchanges the `_dhc_session` cookie for this token via
  `GET /api/auth/socket-token` and passes it to the Phoenix JS socket as
  `authToken`. The socket verifies it through
  `get_principal_by_socket_token/1`. Single-use is not enforced — the
  `@socket_validity_in_seconds` window is the boundary — but only the hash is
  stored.
  """
  def create_socket_token(%Principal{} = principal) do
    {token, row} = PrincipalToken.build_socket_token(principal)
    {:ok, _} = Repo.insert(row)
    {:ok, token}
  end

  @doc """
  Looks up the Principal for a socket token.

  Returns `{:ok, principal}` if the token exists and was created within the
  socket-token validity window. Returns `{:error, :invalid}` otherwise. The
  caller (the socket `connect/3`) additionally checks `is_active` and roles.
  """
  def get_principal_by_socket_token(token) when is_binary(token) do
    {:ok, query} = PrincipalToken.verify_socket_token_query(token)

    case Repo.one(query) do
      {principal, _row} -> {:ok, principal}
      nil -> {:error, :invalid}
    end
  end

  ## Access projection

  defp eligible_member_locked?(principal_id) do
    UserProfile
    |> where([profile], profile.principal_id == ^principal_id)
    |> select([profile], profile.is_active)
    |> lock("FOR UPDATE")
    |> Repo.one() == true
  end

  defp lock_principal!(principal_id) do
    from(principal in Principal, where: principal.id == ^principal_id, lock: "FOR UPDATE")
    |> Repo.one()
    |> case do
      %Principal{} = principal -> principal
      nil -> Repo.rollback(:invalid)
    end
  end

  defp linked_member_principal_locked(principal_id) do
    from(principal in Principal,
      join: profile in UserProfile,
      on: profile.principal_id == principal.id,
      join: member in MemberProfile,
      on: member.user_profile_id == profile.id and member.id == principal.id,
      where: principal.id == ^principal_id,
      select: principal,
      lock: "FOR UPDATE"
    )
    |> Repo.one()
  end

  defp transaction_result({:ok, result}), do: {:ok, result}
  defp transaction_result({:error, _reason}), do: {:error, :invalid}

  # Deferred cross-table constraint triggers may reject at COMMIT rather than
  # at Repo.insert/2. OAuth callers must still receive the same neutral result
  # and never an exception that distinguishes a collision from an unknown
  # account or failed proof.
  defp safe_discord_transaction(fun) do
    Repo.transaction(fun)
  rescue
    Postgrex.Error -> {:error, :invalid}
    Ecto.ConstraintError -> {:error, :invalid}
  end

  @doc """
  Loads the access projection for a Principal: current roles and the
  `is_active` flag.

  Returns `{:ok, %{principal: principal, roles: [String.t()], is_active: boolean}}`
  or `{:error, :no_profile}` if the Principal has no `user_profiles` row —
  which means it cannot have club access, so the request plug treats it as
  `401`.

  Roles come from `user_roles` (live on every request, per the spec). The
  `is_active` flag is the Stripe-driven projection on `user_profiles` (see
  CONTEXT.md — DHC does not set it directly).

  Application ownership points directly at `principals.id` after M2.
  """
  def load_session_principal(principal) do
    query =
      from p in Principal,
        left_join: profile in "user_profiles",
        on: profile.principal_id == p.id,
        left_join: ur in "user_roles",
        on: ur.principal_id == p.id,
        where: p.id == ^principal.id,
        group_by: [p.id, profile.is_active],
        select: %{
          principal: p,
          is_active: profile.is_active,
          roles: fragment("array_agg(?)", ur.role)
        }

    case Repo.one(query) do
      nil ->
        {:error, :no_profile}

      %{principal: _principal, is_active: nil} ->
        # Left join produced a row (the Principal exists) but no user_profiles
        # matched — the Principal has no Member profile, so it has no club
        # access. Treat as no_profile: the request plug returns 401.
        {:error, :no_profile}

      %{principal: principal, is_active: is_active, roles: roles} ->
        roles = roles |> Enum.filter(&is_binary/1) |> Enum.reject(&(&1 == ""))
        {:ok, %{principal: principal, is_active: is_active, roles: roles}}
    end
  end
end
