defmodule Dhc.AuthFixtures do
  @moduledoc """
  Test helpers for the Phoenix-owned auth foundation (ALE-165).

  Inserts Principals, magic-link tokens, and session tokens directly through
  the `Dhc.Auth` context. Member / `user_profiles` rows are created with
  `Dhc.MemberFixtures.member_fixture/1` when an access projection is needed —
  that helper wires the `auth.users` + `user_profiles` + `member_profiles`
  rows the existing test harness expects.

  The `principal_fixture/1` helper takes an optional `:auth_user_id` so a
  Principal can share a UUID with an existing `auth.users` row (the post-M1
  shape: `principals.id == auth.users.id == user_profiles.supabase_user_id`).
  """

  alias Dhc.Auth
  alias Dhc.Auth.Principal
  alias Dhc.Repo

  import Ecto.Query

  def unique_principal_email, do: "principal-#{System.unique_integer([:positive])}@example.com"

  @doc """
  Inserts a Principal. Options:

    * `:email` - override (default: auto-generated unique)
    * `:id` - explicit UUID (e.g. to match an existing `auth.users.id`)
    * `:confirmed_at` - override (default: now, so the Principal is already
      confirmed; pass `nil` to test first-link confirmation)
  """
  def principal_fixture(attrs \\ %{}) do
    attrs =
      Enum.into(attrs, %{
        email: unique_principal_email()
      })

    {:ok, principal} = Auth.register_principal(%{email: attrs.email})

    principal =
      case attrs do
        %{confirmed_at: nil} -> principal
        _ -> confirm_principal(principal)
      end

    # Allow overriding the id after insert so tests can align it with an
    # existing auth.users.id (the post-M1 invariant). We update the row
    # directly rather than passing `:id` through the changeset because
    # `email_changeset/2` doesn't cast `:id` (autogenerated).
    principal =
      case Map.get(attrs, :id) do
        nil -> principal
        id -> set_principal_id(principal, id)
      end

    principal
  end

  defp confirm_principal(principal) do
    {:ok, principal} =
      principal
      |> Principal.confirm_changeset()
      |> Repo.update()

    principal
  end

  defp set_principal_id(principal, id) do
    # Update the PK to the requested UUID, then re-fetch. We re-fetch rather
    # than rely on `returning: true` because the latter has produced
    # `{count, nil}` in this repo's test sandbox (the RETURNING clause does
    # not appear in the generated SQL for this Ecto/Postgrex combination).
    {1, _} =
      Repo.update_all(
        from(p in Principal, where: p.id == ^principal.id),
        set: [id: id]
      )

    Repo.get!(Principal, id)
  end

  @doc """
  Builds and inserts a magic-link token for `principal`. Returns the
  URL-safe encoded token (the value that would be emailed) and the raw row.
  """
  def magic_link_token(principal) do
    {encoded, row} = Dhc.Auth.PrincipalToken.build_magic_link_token(principal)
    {:ok, _} = Repo.insert(row)
    {encoded, row}
  end

  @doc """
  Builds and inserts a session token for `principal`. Returns the raw opaque
  token (the value placed in the signed cookie).
  """
  def session_token(principal) do
    {:ok, token} = Auth.create_session(principal)
    token
  end

  @doc """
  Ages a token row's `created_at` back or forward by `amount` `unit`, so
  expiry tests can run without real sleeps. `token` is the raw bytes (for
  session tokens) or the hashed bytes (for magic-link tokens — pass
  `row.token`).
  """
  def age_token(token, amount, unit) do
    dt = DateTime.add(DateTime.utc_now(:second), amount, unit)

    Repo.update_all(
      from(t in Dhc.Auth.PrincipalToken, where: t.token == ^token),
      set: [created_at: dt]
    )
  end
end
