defmodule Dhc.Auth.UserRole do
  @moduledoc false

  use Ecto.Schema

  # `user_roles.id` is `bigint GENERATED BY DEFAULT AS IDENTITY` (see migration
  # `20260512000004_create_users_and_roles.exs`). Ecto's `:id` type maps to a
  # serial/bigint primary key, which is compatible with IDENTITY columns as
  # long as we don't try to autogenerate the id ourselves — Postgres fills it.
  @primary_key {:id, :id, autogenerate: false}

  @type t :: %__MODULE__{}

  schema "user_roles" do
    field :user_id, :binary_id
    field :role, :string
  end
end
