// Entire CLI plugin for OpenCode
// Auto-generated by `entire enable --agent opencode`
// Do not edit manually — changes will be overwritten on next install.
// Requires Bun runtime (used by OpenCode's plugin system for loading ESM plugins).
import { Plugin } from "@opencode-ai/plugin"

export const EntirePlugin = Plugin.define({
  id: "entire",
  async setup(ctx) {
  const ENTIRE_CMD = "entire"
  const directory = ctx.location.directory
  let currentSessionID: string | null = null
  let currentModel: string | null = null
  // One-time model-context injection captured from the turn-start hook's stdout,
  // applied on the next LLM call via experimental.chat.system.transform.
  let pendingInjection: string | null = null

  /**
   * Build the shell command for a hook invocation.
   * Uses sh -c so that shell command substitution in ENTIRE_CMD
   * (e.g., $(git rev-parse --show-toplevel) for local-dev) is interpreted.
   */
  function hookCmd(hookName: string): string[] {
    if (ENTIRE_CMD !== "entire") {
      return ["sh", "-c", `${ENTIRE_CMD} hooks opencode ${hookName}`]
    }
    return ["sh", "-c", `if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks opencode ${hookName}`]
  }

  /**
   * Pipe JSON payload to an entire hooks command (async).
   * Errors are logged but never thrown — plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const proc = Bun.spawn(hookCmd(hookName), {
        cwd: directory,
        stdin: new Blob([json + "\n"]),
        stdout: "ignore",
        stderr: "ignore",
      })
      await proc.exited
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  /**
   * Synchronous variant for hooks that must complete before subsequent agent work
   * or process exit. `turn-start` must finish initializing session state before a
   * fast mid-turn commit can hit git hooks, and `turn-end` / `session-end` must
   * finish before `opencode run` tears down its event loop.
   */
  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      Bun.spawnSync(hookCmd(hookName), {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  // parseInjectedContext scans a hook's stdout for Entire's injection envelope
  // ({"inject_context":"..."}) and returns the text to inject, or null.
  function parseInjectedContext(stdout: string): string | null {
    if (!stdout) return null
    for (const line of stdout.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed.startsWith("{")) continue
      try {
        const parsed = JSON.parse(trimmed) as { inject_context?: unknown }
        if (typeof parsed.inject_context === "string" && parsed.inject_context.length > 0) {
          return parsed.inject_context
        }
      } catch {
        // not our envelope — ignore
      }
    }
    return null
  }

  // fireTurnStart fires turn-start synchronously (state must be ready before
  // mid-turn commits) and stashes any model-context injection emitted on stdout
  // for experimental.chat.system.transform to apply. Entire emits the injection
  // at most once per session, so pendingInjection is set on the first turn only.
  function fireTurnStart(payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const proc = Bun.spawnSync(hookCmd("turn-start"), {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "pipe",
        stderr: "ignore",
      })
      const out = proc.stdout ? proc.stdout.toString() : ""
      const injected = parseInjectedContext(out)
      if (injected) pendingInjection = injected
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  function resetSessionTracking(sessionID: string) {
    if (currentSessionID === sessionID) {
      return false
    }
    currentModel = null
    currentSessionID = sessionID
    return true
  }

  function modelName(model: { providerID: string; id: string; variant?: string }) {
    return `${model.providerID}/${model.id}${model.variant ? `#${model.variant}` : ""}`
  }

  await ctx.session.hook("prompt", async (event) => {
    if (resetSessionTracking(event.sessionID)) {
      callHookSync("session-start", { session_id: event.sessionID })
    }

    try {
      const session = await ctx.session.get({ sessionID: event.sessionID })
      if (session.model) currentModel = modelName(session.model)
    } catch {
      // The session can still proceed when model metadata is unavailable.
    }

    fireTurnStart({
      session_id: event.sessionID,
      prompt: event.prompt.text,
      model: currentModel ?? "",
    })
  })

  await ctx.session.hook("context", (event) => {
    if (!pendingInjection) return
    event.system.push({ text: pendingInjection })
    pendingInjection = null
  })

  const controller = new AbortController()
  void (async () => {
    try {
      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
        switch (event.type) {
          case "session.created": {
            const { sessionID, model } = event.data
            if (resetSessionTracking(sessionID)) {
              callHookSync("session-start", { session_id: sessionID })
            }
            if (model) currentModel = modelName(model)
            break
          }

          case "session.model.selected":
          case "session.step.started": {
            currentSessionID = event.data.sessionID
            currentModel = modelName(event.data.model)
            break
          }

          case "session.status": {
            if (event.data.status.type !== "idle") break
            callHookSync("turn-end", {
              session_id: event.data.sessionID,
              model: currentModel ?? "",
            })
            break
          }

          case "session.compaction.ended": {
            await callHook("compaction", { session_id: event.data.sessionID })
            break
          }

          case "session.deleted": {
            callHookSync("session-end", { session_id: event.data.sessionID })
            if (currentSessionID === event.data.sessionID) {
              currentSessionID = null
              currentModel = null
            }
            break
          }
        }
      }
    } catch {
      // Aborts and event-stream failures must not crash OpenCode.
    }
  })()

  return () => {
    controller.abort()
    if (!currentSessionID) return
    callHookSync("session-end", { session_id: currentSessionID })
    currentSessionID = null
    currentModel = null
  }
  },
})
