defmodule Dhc.MemberProfiles.MemberProfile do
  @moduledoc """
  Ecto schema for the `member_profiles` table.

  Maps the full `member_profiles` column set so the schema is reusable by both
  the members-list read and the later replacement of raw `"member_profiles"`
  string access in `stripe_sync` and the seed tasks.

  The table is owned by the application (created by the baseline Ecto
  migration `20260512000005_create_member_profiles`). The primary key is a
  `uuid` that references `auth.users(id)` with `ON DELETE NOTHING`, so it is
  **not** autogenerated — it is set from the Supabase auth user id on insert.
  """

  use Ecto.Schema

  @primary_key {:id, :binary_id, autogenerate: false}
  @foreign_key_type :binary_id
  @type t :: %__MODULE__{}

  schema "member_profiles" do
    field :user_profile_id, :binary_id
    field :next_of_kin_name, :string
    field :next_of_kin_phone, :string
    field :preferred_weapon, {:array, :string}
    field :membership_start_date, :utc_datetime
    field :membership_end_date, :utc_datetime
    field :last_payment_date, :utc_datetime
    field :insurance_form_submitted, :boolean, default: false
    field :additional_data, :map, default: %{}
    field :subscription_paused_until, :utc_datetime

    timestamps(type: :utc_datetime, inserted_at: :created_at)
  end
end
