// @dhc/api-client - Generated TypeScript SDK for DHC Dashboard API
//
// Re-exports everything from the generated client.
// Use `configureClient()` to set base URL and auth token.

// Generated SDK functions & types
export {
  healthIndex,
  invitationsCreate,
  invitationsList,
  invitationsResend,
  membersAnalytics,
  membersInsuranceForm,
  membersList,
  notificationsList,
  stripeWebhooksCreate,
  waitlistAnalytics,
  waitlistEntries,
  waitlistStatus,
  workshopsCalendar,
  workshopsList,
  type Options,
} from "./client/sdk.gen";
export type {
  ClientOptions,
  HealthIndexData,
  HealthIndexResponse,
  HealthIndexResponses,
  Invitation,
  InvitationCreateInvite,
  InvitationCreateRequest,
  InvitationCreateResponse,
  InvitationListResponse,
  InvitationListSortField,
  InvitationResendCreateRequest,
  InvitationResendCreateResponse,
  InvitationStatus,
  InvitationsCreateData,
  InvitationsCreateError,
  InvitationsCreateErrors,
  InvitationsCreateResponse,
  InvitationsCreateResponses,
  InvitationsListData,
  InvitationsListError,
  InvitationsListErrors,
  InvitationsListResponse,
  InvitationsListResponses,
  InvitationsResendData,
  InvitationsResendError,
  InvitationsResendErrors,
  InvitationsResendResponse,
  InvitationsResendResponses,
  MembersAgeDistributionItem,
  MembersAnalyticsData,
  MembersAnalyticsError,
  MembersAnalyticsErrors,
  MembersAnalyticsResponse,
  MembersAnalyticsResponse2,
  MembersAnalyticsResponses,
  MembersGenderDistributionItem,
  MembersInsuranceFormData,
  MembersInsuranceFormError,
  MembersInsuranceFormErrors,
  MembersInsuranceFormResponse,
  MembersInsuranceFormResponse2,
  MembersInsuranceFormResponses,
  MembersListData,
  MembersListError,
  MembersListErrors,
  MembersListResponse,
  MembersListResponse2,
  MembersListResponses,
  MembersListSortField,
  MembersWeaponDistributionItem,
  Member,
  Notification,
  NotificationsListData,
  NotificationsListError,
  NotificationsListErrors,
  NotificationsListResponse,
  NotificationsListResponse2,
  NotificationsListResponses,
  StripeWebhooksCreateData,
  StripeWebhooksCreateError,
  StripeWebhooksCreateErrors,
  StripeWebhooksCreateResponse,
  StripeWebhooksCreateResponses,
  WaitlistStatusData,
  WaitlistAnalyticsData,
  WaitlistAnalyticsError,
  WaitlistAnalyticsErrors,
  WaitlistAnalyticsResponse,
  WaitlistAnalyticsResponse2,
  WaitlistAnalyticsResponses,
  WaitlistAgeDistributionItem,
  WaitlistEntriesData,
  WaitlistEntriesError,
  WaitlistEntriesErrors,
  WaitlistEntriesResponse,
  WaitlistEntriesResponse2,
  WaitlistEntriesResponses,
  WaitlistEntriesSortField,
  WaitlistEntry,
  WaitlistGenderDistributionItem,
  WaitlistStatus,
  WaitlistStatusResponse,
  WaitlistStatusResponse2,
  WaitlistStatusResponses,
  RegistrationStatus,
  Workshop,
  WorkshopCalendarItem,
  WorkshopRegistration,
  WorkshopsCalendarData,
  WorkshopsCalendarError,
  WorkshopsCalendarErrors,
  WorkshopsCalendarResponse,
  WorkshopsCalendarResponses,
  WorkshopsListData,
  WorkshopsListError,
  WorkshopsListErrors,
  WorkshopsListResponse,
  WorkshopsListResponse2,
  WorkshopsListResponses,
  WorkshopStatus,
} from "./client/types.gen";

// Valibot schemas (runtime validation)
export {
  vHealthIndexResponse,
  vInvitation,
  vInvitationCreateInvite,
  vInvitationCreateRequest,
  vInvitationCreateResponse,
  vInvitationListResponse,
  vInvitationListSortField,
  vInvitationResendCreateRequest,
  vInvitationResendCreateResponse,
  vInvitationStatus,
  vInvitationsCreateBody,
  vInvitationsCreateResponse,
  vInvitationsListQuery,
  vInvitationsListResponse,
  vInvitationsResendBody,
  vInvitationsResendResponse,
  vMembersAgeDistributionItem,
  vMembersAnalyticsResponse,
  vMembersAnalyticsResponse2,
  vMembersGenderDistributionItem,
  vMembersInsuranceFormResponse,
  vMembersInsuranceFormResponse2,
  vMembersListQuery,
  vMembersListResponse,
  vMembersListResponse2,
  vMembersListSortField,
  vMembersWeaponDistributionItem,
  vMember,
  vNotification,
  vNotificationsListQuery,
  vNotificationsListResponse,
  vNotificationsListResponse2,
  vStripeWebhooksCreateBody,
  vStripeWebhooksCreateResponse,
  vWaitlistAgeDistributionItem,
  vWaitlistAnalyticsResponse,
  vWaitlistAnalyticsResponse2,
  vWaitlistEntriesQuery,
  vWaitlistEntriesResponse,
  vWaitlistEntriesResponse2,
  vWaitlistEntry,
  vWaitlistEntriesSortField,
  vWaitlistGenderDistributionItem,
  vWaitlistStatus,
  vWaitlistStatusResponse,
  vWaitlistStatusResponse2,
  vRegistrationStatus,
  vWorkshop,
  vWorkshopCalendarItem,
  vWorkshopCalendarResponse,
  vWorkshopRegistration,
  vWorkshopsCalendarResponse,
  vWorkshopsListQuery,
  vWorkshopsListResponse,
  vWorkshopsListResponse2,
  vWorkshopStatus,
} from "./client/valibot.gen";

// TanStack Svelte Query helpers
export {
  healthIndexOptions,
  healthIndexQueryKey,
  invitationsCreateMutation,
  invitationsCreateMutationKey,
  invitationsListInfiniteOptions,
  invitationsListInfiniteQueryKey,
  invitationsListOptions,
  invitationsListQueryKey,
  invitationsResendMutation,
  invitationsResendMutationKey,
  membersAnalyticsOptions,
  membersAnalyticsQueryKey,
  membersInsuranceFormOptions,
  membersInsuranceFormQueryKey,
  membersListInfiniteOptions,
  membersListInfiniteQueryKey,
  membersListOptions,
  membersListQueryKey,
  notificationsListInfiniteOptions,
  notificationsListInfiniteQueryKey,
  notificationsListOptions,
  notificationsListQueryKey,
  stripeWebhooksCreateMutation,
  stripeWebhooksCreateMutationKey,
  waitlistAnalyticsOptions,
  waitlistAnalyticsQueryKey,
  waitlistEntriesOptions,
  waitlistEntriesQueryKey,
  waitlistStatusOptions,
  waitlistStatusQueryKey,
  workshopsCalendarOptions,
  workshopsCalendarQueryKey,
  workshopsListOptions,
  workshopsListQueryKey,
  type QueryKey,
} from "./client/@tanstack/svelte-query.gen";

// Client configuration
export { configureClient, getClient } from "./config";
export type { ClientConfig, SupabaseJwtGetter } from "./config";

// Low-level client (for interceptors, custom requests)
export { client } from "./client/client.gen";
